### ISSUE TITLE
Accessing Youtube API

### ISSUE THREAD

**Issue by damoun** [juliussohn/react-youtube-background-player#1]
Hi,

In the current state, we cannot access the Youtube API through your component like react-youtube, isn't it ?
Could it be possible to add the event parameter to the event function (onEnd, onReady, etc.) to the props ? https://github.com/juliussohn/react-youtube-background/blob/master/src/index.js#L61

I would like to use your component but I cannot use the seekTo function from the Youtube API.

**Comment by juliussohn** [comment]
added all events in v0.2.0
the events return the player object, that can be used to control the player
`onReady, onEnd, onPlay, onPause, onError, onStateChange, onPlaybackRateChange, onPlaybackQualityChange`
